Repository heroui-inc/heroui, pull requests merged in 2022-04, with the labels that each got.

#382 Input {required} parameter fix (again)
  apps/docs/content/docs/components/button.mdx
  packages/react/src/input/input.tsx
Labels: bugfix

#384 Refactor/button migration to react aria
  apps/docs/content/components/button/loading.ts
  apps/docs/content/docs/components/button.mdx
  apps/docs/content/docs/components/loading.mdx
  packages/react/package.json
  packages/react/src/button/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/icon.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/button/__tests__/index.test.tsx
  packages/react/src/button/button.stories.tsx
  packages/react/src/button/button.styles.ts
  packages/react/src/button/button.tsx
  packages/react/src/button/utils.tsx
  packages/react/src/loading/loading.styles.ts
  packages/react/src/loading/loading.tsx
  packages/react/src/theme/stitches.config.ts
  packages/react/src/use-drip/use-drip.ts
  packages/react/src/utils/dom.ts
  yarn.lock
Labels: type:nextui, a11y, refactor

#383 Fix/no margin pagination
  apps/docs/src/components/hero/components.tsx
  apps/docs/src/components/theme-switch/index.tsx
  packages/react/src/pagination/pagination.styles.ts
Labels: bugfix

#385 v1.0.6-beta.5
  apps/docs/content/components/button/loading.ts
  apps/docs/content/docs/components/button.mdx
  apps/docs/content/docs/components/loading.mdx
  apps/docs/package.json
  apps/docs/src/components/hero/components.tsx
  apps/docs/src/components/theme-switch/index.tsx
  examples/create-next-app/package.json
  examples/create-react-app/package.json
  examples/vite-react-typescript/package.json
  packages/react/package.json
  packages/react/src/backdrop/backdrop.styles.ts
  packages/react/src/backdrop/backdrop.tsx
  packages/react/src/button/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/icon.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/button/__tests__/index.test.tsx
  packages/react/src/button/button.stories.tsx
  packages/react/src/button/button.styles.ts
  packages/react/src/button/button.tsx
  packages/react/src/button/utils.tsx
  packages/react/src/input/input.tsx
  packages/react/src/loading/loading.styles.ts
  packages/react/src/loading/loading.tsx
  packages/react/src/modal/modal.stories.tsx
  packages/react/src/modal/modal.tsx
  packages/react/src/pagination/pagination.styles.ts
  packages/react/src/theme/stitches.config.ts
  packages/react/src/use-drip/use-drip.ts
  packages/react/src/utils/dom.ts
  packages/storybook/package.json
  yarn.lock
Labels: feature, bugfix

#388 Fix/avatar container margin
  apps/docs/content/docs/components/button.mdx
  packages/react/src/avatar/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/avatar/avatar.styles.ts
  packages/react/src/theme/common.ts
Labels: bugfix

#390 Refactor/checkbox migration to react aria
  apps/docs/content/components/checkbox-group/column.ts
  apps/docs/content/components/checkbox-group/controlled-vs-uncontrolled.ts
  apps/docs/content/components/checkbox-group/events.ts
  apps/docs/content/components/checkbox-group/index.ts
  apps/docs/content/components/checkbox-group/row.ts
  apps/docs/content/components/checkbox/checkbox-group.ts
  apps/docs/content/components/checkbox/color.ts
  apps/docs/content/components/checkbox/controlled-vs-uncontrolled.ts
  apps/docs/content/components/checkbox/default.ts
  apps/docs/content/components/checkbox/disabled.ts
  apps/docs/content/components/checkbox/index.ts
  apps/docs/content/components/checkbox/interminate.ts
  apps/docs/content/components/checkbox/label-color.ts
  apps/docs/content/components/checkbox/line-through.ts
  apps/docs/content/components/checkbox/no-animated.ts
  apps/docs/content/components/checkbox/rounded.ts
  apps/docs/content/components/checkbox/row-group.ts
  apps/docs/content/components/checkbox/size.ts
  apps/docs/content/components/index.ts
  apps/docs/content/docs/components/checkbox-group.mdx
  apps/docs/content/docs/components/checkbox.mdx
  apps/docs/content/docs/components/textarea.mdx
  apps/docs/content/docs/guide/getting-started.mdx
  apps/docs/content/docs/manifest.json
  apps/docs/src/components/nav-link/index.tsx
  apps/docs/src/components/sidebar/index.tsx
  apps/docs/src/components/sidebar/post.tsx
  packages/react/package.json
  packages/react/src/button/__tests__/index.test.tsx
  packages/react/src/card/card.styles.ts
  packages/react/src/checkbox/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/checkbox/__tests__/group.test.tsx
  packages/react/src/checkbox/__tests__/index.test.tsx
  packages/react/src/checkbox/checkbox-context.ts
  packages/react/src/checkbox/checkbox-group.tsx
  packages/react/src/checkbox/checkbox.stories.tsx
  packages/react/src/checkbox/checkbox.styles.ts
  packages/react/src/checkbox/checkbox.tsx
  packages/react/src/checkbox/index.ts
  packages/react/src/checkbox/utils.ts
  packages/react/src/link/link.styles.ts
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/table/table-checkbox-cell.tsx
  packages/react/src/table/table-select-all-checkbox.tsx
  packages/react/src/table/table.styles.ts
  packages/react/src/table/utils.ts
  packages/react/src/theme/common.ts
  packages/react/src/utils/dom.ts
  yarn.lock
Labels: a11y, refactor

#393 v1.0.7-beta.5
  .github/stale.yml
  apps/docs/content/components/checkbox-group/column.ts
  apps/docs/content/components/checkbox-group/controlled-vs-uncontrolled.ts
  apps/docs/content/components/checkbox-group/events.ts
  apps/docs/content/components/checkbox-group/index.ts
  apps/docs/content/components/checkbox-group/row.ts
  apps/docs/content/components/checkbox/checkbox-group.ts
  apps/docs/content/components/checkbox/color.ts
  apps/docs/content/components/checkbox/controlled-vs-uncontrolled.ts
  apps/docs/content/components/checkbox/default.ts
  apps/docs/content/components/checkbox/disabled.ts
  apps/docs/content/components/checkbox/index.ts
  apps/docs/content/components/checkbox/interminate.ts
  apps/docs/content/components/checkbox/label-color.ts
  apps/docs/content/components/checkbox/line-through.ts
  apps/docs/content/components/checkbox/no-animated.ts
  apps/docs/content/components/checkbox/rounded.ts
  apps/docs/content/components/checkbox/row-group.ts
  apps/docs/content/components/checkbox/size.ts
  apps/docs/content/components/index.ts
  apps/docs/content/docs/components/checkbox-group.mdx
  apps/docs/content/docs/components/checkbox.mdx
  apps/docs/content/docs/components/textarea.mdx
  apps/docs/content/docs/guide/getting-started.mdx
  apps/docs/content/docs/manifest.json
  apps/docs/package.json
  apps/docs/src/components/nav-link/index.tsx
  apps/docs/src/components/sidebar/index.tsx
  apps/docs/src/components/sidebar/post.tsx
  examples/create-next-app/package.json
  examples/create-react-app/package.json
  examples/vite-react-typescript/package.json
  packages/react/package.json
  packages/react/src/avatar/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/avatar/avatar.styles.ts
  packages/react/src/button/__tests__/index.test.tsx
  packages/react/src/card/card.styles.ts
  packages/react/src/checkbox/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/checkbox/__tests__/group.test.tsx
  packages/react/src/checkbox/__tests__/index.test.tsx
  packages/react/src/checkbox/checkbox-context.ts
  packages/react/src/checkbox/checkbox-group.tsx
  packages/react/src/checkbox/checkbox.stories.tsx
  packages/react/src/checkbox/checkbox.styles.ts
  packages/react/src/checkbox/checkbox.tsx
  packages/react/src/checkbox/index.ts
  packages/react/src/checkbox/utils.ts
  packages/react/src/link/link.styles.ts
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/table/table-checkbox-cell.tsx
  packages/react/src/table/table-select-all-checkbox.tsx
  packages/react/src/table/table.styles.ts
  packages/react/src/table/utils.ts
  packages/react/src/theme/common.ts
  packages/react/src/utils/dom.ts
  packages/storybook/package.json
  yarn.lock
Labels: core, a11y, refactor

#422 Fix 406/table overflow
  apps/docs/src/components/palette/index.tsx
  apps/docs/src/components/palette/item.tsx
  packages/react/src/table/table.styles.ts
Labels: refactor

#425 Container typo
  packages/react/src/grid/grid-container.tsx
Labels: fix:typo

#416 add remix example
  examples/create-remix-app/.gitignore
  examples/create-remix-app/README.md
  examples/create-remix-app/api/index.js.map
  examples/create-remix-app/app/entry.client.tsx
  examples/create-remix-app/app/entry.server.tsx
  examples/create-remix-app/app/root.tsx
  examples/create-remix-app/app/routes/index.tsx
  examples/create-remix-app/package.json
  examples/create-remix-app/public/favicon.ico
  examples/create-remix-app/remix.config.js
  examples/create-remix-app/remix.env.d.ts
  examples/create-remix-app/server.js
  examples/create-remix-app/tsconfig.json
  examples/create-remix-app/vercel.json
Labels: reviewing

#434 fix: #291 stitches compatability with typescript
  packages/react/package.json
  yarn.lock
Labels: bugfix
