Repository heroui-inc/heroui, pull requests merged in 2022-08, with the labels that each got.

#684 fix(table): Table.Header column border radius size #677
  packages/react/src/table/table.styles.ts
Labels: bugfix

#709 refactor(react-checkbox): new prop added to manage the container css
  .github/stale.yml
  apps/docs/content/components/checkbox-group/controlled-vs-uncontrolled.ts
  apps/docs/content/components/checkbox/color.ts
  apps/docs/content/components/checkbox/controlled-vs-uncontrolled.ts
  apps/docs/content/components/checkbox/default.ts
  apps/docs/content/components/checkbox/disabled.ts
  apps/docs/content/components/checkbox/interminate.ts
  apps/docs/content/components/checkbox/label-color.ts
  apps/docs/content/components/checkbox/line-through.ts
  apps/docs/content/components/checkbox/no-animated.ts
  apps/docs/content/components/checkbox/rounded.ts
  apps/docs/content/components/checkbox/size.ts
  apps/docs/content/docs/components/checkbox.mdx
  apps/docs/content/docs/manifest.json
  apps/docs/src/components/search/suggestion.tsx
  packages/react/src/checkbox/checkbox.styles.ts
  packages/react/src/checkbox/checkbox.tsx
  packages/react/src/checkbox/use-checkbox.ts
Labels: core, refactor

#711 fix(react-radio): radio group isRequired prop passed directly to the …
  packages/react/src/radio/use-radio-group.ts
Labels: bugfix

#716 Fix 389/table user select
  apps/docs/content/components/navbar/variants.ts
  apps/docs/src/pages/examples/navbar/variants.tsx
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/table/__tests__/index.test.tsx
  packages/react/src/table/table-body.tsx
  packages/react/src/table/table-cell.tsx
  packages/react/src/table/table.stories.tsx
  packages/react/src/table/table.styles.ts
  packages/react/src/table/table.tsx
Labels: a11y, bugfix, pending release
