Repository heroui-inc/heroui, pull requests merged in 2022-05, with the labels that each got.

#443 Refactor/theme palette
  apps/docs/content/components/table/custom-cells.ts
  apps/docs/content/components/text/gradient.ts
  apps/docs/content/components/tooltip/customContent.ts
  apps/docs/content/docs/components/button.mdx
  apps/docs/content/docs/theme/customize-theme.mdx
  apps/docs/content/docs/theme/default-theme.mdx
  apps/docs/content/landing/index.tsx
  apps/docs/src/components/anchor/index.tsx
  apps/docs/src/components/badge/badge.styles.ts
  apps/docs/src/components/code-demo/code-block.tsx
  apps/docs/src/components/code-demo/pre.tsx
  apps/docs/src/components/community/community.tsx
  apps/docs/src/components/features-grid/features-grid.tsx
  apps/docs/src/components/hero/components.tsx
  apps/docs/src/components/hero/styles.ts
  apps/docs/src/components/home/built-in-stitches.tsx
  apps/docs/src/components/home/customization.tsx
  apps/docs/src/components/home/dark-mode.tsx
  apps/docs/src/components/mdx/index.tsx
  apps/docs/src/components/palette/index.tsx
  apps/docs/src/components/primitives/index.ts
  apps/docs/src/components/sandpack/themes.ts
  apps/docs/src/components/search/autocomplete.tsx
  apps/docs/src/components/sidebar/category.tsx
  apps/docs/src/components/sidebar/post.tsx
  apps/docs/src/components/table-of-content/index.tsx
  apps/docs/src/components/templates/custom-button/index.tsx
  apps/docs/src/components/templates/shop-card/styles.ts
  apps/docs/src/components/templates/user-twitter-card/index.tsx
  apps/docs/src/components/theme-toggle/index.tsx
  apps/docs/src/layouts/footer.tsx
  apps/docs/src/layouts/styles.ts
  apps/docs/src/theme/shared.ts
  packages/react/src/button/button.styles.ts
  packages/react/src/button/utils.tsx
  packages/react/src/checkbox/checkbox.styles.ts
  packages/react/src/collapse/collapse.styles.ts
  packages/react/src/css-baseline/css-baseline.tsx
  packages/react/src/index.ts
  packages/react/src/input/input.styles.ts
  packages/react/src/pagination/pagination.styles.ts
  packages/react/src/radio/radio.styles.ts
  packages/react/src/switch/switch.styles.ts
  packages/react/src/table/table.stories.tsx
  packages/react/src/table/table.styles.ts
  packages/react/src/theme/colors/blue.ts
  packages/react/src/theme/colors/cyan.ts
  packages/react/src/theme/colors/gray.ts
  packages/react/src/theme/colors/green.ts
  packages/react/src/theme/colors/index.ts
  packages/react/src/theme/colors/pink.ts
  packages/react/src/theme/colors/purple.ts
  packages/react/src/theme/colors/red.ts
  packages/react/src/theme/colors/yellow.ts
  packages/react/src/theme/common.ts
  packages/react/src/theme/dark-theme.ts
  packages/react/src/theme/index.ts
  packages/react/src/theme/light-theme.ts
  packages/react/src/user/user.styles.ts
Labels: a11y, refactor

#440 fix: #439 server side rendering of table with pagination
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/table/table-context.tsx
  packages/react/src/table/table.tsx
  packages/react/src/table/utils.ts
Labels: bugfix, reviewing

#444 fix(react-card): :first-child/:last-child margin was removed
  packages/react/src/card/card.styles.ts
  packages/react/src/theme/common.ts
Labels: core, bugfix

#445 fix: ghost button fixed on mobile
  packages/react/src/button/button.styles.ts
  packages/react/src/button/button.tsx
Labels: core, bugfix

#446 fix(react-link): wrap it into a single child
  packages/react/src/link/link.tsx
Labels: core, bugfix

#447 Fix 426/button onclick keyboard
  packages/react/src/button/button.tsx
Labels: core, bugfix

#448 Fix 431/checkbox initial checked
  packages/react/src/checkbox/checkbox.tsx
Labels: core, bugfix

#459 fix(react-popover): The content of the popover appears blurred Closes…
  packages/react/src/popover/popover-content.tsx
  packages/react/src/popover/popover.styles.ts
Labels: core, bugfix

#460 Fix 456/unblurred menu bar firefox
  apps/docs/src/components/hero/index.tsx
  apps/docs/src/components/mobile-navigation/index.tsx
  apps/docs/src/components/primitives/index.ts
  apps/docs/src/components/search/autocomplete.tsx
  apps/docs/src/layouts/styles.ts
  packages/react/src/backdrop/backdrop.styles.ts
  packages/react/src/modal/modal.stories.tsx
Labels: core, bugfix

#452 Update getting-started.mdx
  apps/docs/content/docs/guide/getting-started.mdx
Labels: type:docs-src, refactor

#451 fix #391
  packages/react/src/link/link.styles.ts
Labels: bugfix

#471 Feat/add support button
  apps/docs/src/components/search/autocomplete.tsx
  apps/docs/src/layouts/navbar.tsx
  apps/docs/src/utils/animations.ts
  packages/react/src/checkbox/checkbox.styles.ts
Labels: core, type:docs-src

#483 Refactor/theme gray scale
  apps/docs/src/components/playground/code-theme.ts
  apps/docs/src/components/playground/editor.tsx
  apps/docs/src/components/sidebar/post.tsx
  apps/docs/src/theme/shared.ts
  packages/react/src/theme/colors/gray.ts
Labels: pending release

#485 theme: Amend utility function `bgBlur` to not modulate background value
  apps/docs/content/components/card/cover.ts
  apps/docs/content/docs/theme/utilities.mdx
  apps/docs/content/landing/index.tsx
  packages/react/src/card/card.stories.tsx
  packages/react/src/theme/common.ts
Labels: pending release, breaking changes
