Repository heroui-inc/heroui, pull requests merged in 2022-06, with the labels that each got.

#491 refactor(react-radio): integration with react-aria radio
  apps/docs/content/components/radio/color.ts
  apps/docs/content/components/radio/controlled-vs-uncontrolled.ts
  apps/docs/content/components/radio/default.ts
  apps/docs/content/components/radio/description.ts
  apps/docs/content/components/radio/disabled.ts
  apps/docs/content/components/radio/events.ts
  apps/docs/content/components/radio/index.ts
  apps/docs/content/components/radio/labelColor.ts
  apps/docs/content/components/radio/noAnimation.ts
  apps/docs/content/components/radio/row.ts
  apps/docs/content/components/radio/size.ts
  apps/docs/content/components/radio/squared.ts
  apps/docs/content/components/radio/textColor.ts
  apps/docs/content/docs/components/radio.mdx
  apps/docs/content/docs/manifest.json
  packages/react/package.json
  packages/react/src/radio/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/radio/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/radio/__tests__/group.test.tsx
  packages/react/src/radio/__tests__/index.test.tsx
  packages/react/src/radio/index.ts
  packages/react/src/radio/radio-context.ts
  packages/react/src/radio/radio-desc.tsx
  packages/react/src/radio/radio-group.tsx
  packages/react/src/radio/radio.stories.tsx
  packages/react/src/radio/radio.styles.ts
  packages/react/src/radio/radio.tsx
  packages/react/src/radio/use-radio-group.ts
  packages/react/src/radio/use-radio.ts
  yarn.lock
Labels: a11y, refactor

#466 fix(react-user): prop and link warnings
  packages/react/src/user/index.ts
  packages/react/src/user/user-link.tsx
  packages/react/src/user/user.styles.ts
  packages/react/src/user/user.tsx
Labels: core, bugfix, pending release

#478 fix(docs): missing key in code examples
  apps/docs/content/docs/guide/getting-started.mdx
  apps/docs/content/docs/guide/nextui-plus-nextjs.mdx
Labels: reviewing

#523 fix(react-card): internal components hover and text copy
  packages/react/src/card/card.stories.tsx
  packages/react/src/card/card.tsx
  packages/react/src/card/use-card.ts
Labels: bugfix

#531 Fix 522/ssr provider inconsintent ids
  packages/react/package.json
  yarn.lock
Labels: bugfix, react-aria

#533 v1.0.0-beta.9
  apps/docs/content/docs/components/card.mdx
  apps/docs/package.json
  examples/create-next-app/package.json
  examples/create-react-app/package.json
  examples/vite-react-typescript/package.json
  examples/with-tailwindcss/package.json
  packages/react/package.json
  packages/react/src/button/button.tsx
  packages/react/src/card/card.stories.tsx
  packages/react/src/card/card.tsx
  packages/react/src/card/use-card.ts
  packages/react/src/dropdown/dropdown-trigger.tsx
  packages/react/src/popover/index.ts
  packages/react/src/popover/popover-content.tsx
  packages/react/src/popover/popover-trigger.tsx
  packages/react/src/popover/popover.tsx
  packages/storybook/package.json
  yarn.lock
Labels: bugfix, new version

#563 fix(docs):default value of animated props in avatar group
  apps/docs/content/docs/components/avatar.mdx
Labels: type:docs-md
