Repository heroui-inc/heroui, pull requests merged in 2022-01, with the labels that each got.

#132 Update dark-mode.mdx | Fixed wrong function argument :v:
  apps/docs/content/docs/theme/dark-mode.mdx
Labels: type:docs-md, refactor

#133 fix: theme docs and custom user theme
  apps/docs/content/docs/guide/getting-started.mdx
  apps/docs/content/docs/theme/customize-theme.mdx
  apps/docs/content/docs/theme/dark-mode.mdx
  apps/docs/content/docs/theme/typescript.mdx
  apps/docs/package.json
  apps/docs/public/sitemap.xml
  examples/create-next-app/package.json
  examples/create-react-app/package.json
  packages/react/package.json
  packages/react/src/theme/theme-provider.tsx
  packages/react/src/theme/utils.ts
  packages/storybook/package.json
Labels: bugfix

#137 Fix #136
  apps/docs/content/docs/theme/dark-mode.mdx
  packages/react/src/theme/stitches.config.ts
  packages/react/src/theme/types.ts
Labels: enhancement

#142 fix: community typo
  apps/docs/content/docs/guide/getting-started.mdx
Labels: type:docs-md, fix:typo

#145 fix(button): clear button type forced to type button
  packages/react/src/input/input.tsx
Labels: bugfix

#146 refactor(checkbox): remove default space
  packages/react/src/checkbox/checkbox.tsx
Labels: type:nextui, refactor

#150 fix(nextui): @babel/runtime added as a dependency
  packages/react/package.json
Labels: bugfix

#153 Fix #149
  apps/docs/src/components/fixed/index.tsx
  apps/docs/src/components/index.ts
  apps/docs/src/layouts/docs.tsx
Labels: bugfix

#152 Fix #141
  apps/docs/src/components/nav-link/index.tsx
Labels: bugfix

#182 fix(docs-dark-mode): workaround applied to reduce the switching themes delay
  apps/docs/src/components/hero/index.tsx
  apps/docs/src/components/home/custom-themes.tsx
  apps/docs/src/components/home/dark-mode.tsx
  apps/docs/src/components/templates/player/player.tsx
  apps/docs/src/components/templates/player/styles.ts
  apps/docs/src/pages/index.tsx
  packages/react/src/switch/index.ts
Labels: created-by: NextUI team, type:docs-src, bugfix
