Repository heroui-inc/heroui, pull requests merged in 2022-09, with the labels that each got.

#738 Fix 707/textarea input circular dependecy
  apps/docs/content/components/navbar/common.ts
  packages/react/src/input/index.ts
  packages/react/src/input/input.tsx
Labels: bugfix, pending release

#740 fix(react-dropdown): supports popover content custom css, safari anim…
  apps/docs/content/docs/components/dropdown.mdx
  apps/docs/src/pages/examples/navbar/with-dropdown-menu.tsx
  packages/react/src/dropdown/dropdown-menu.tsx
  packages/react/src/dropdown/dropdown.tsx
  packages/react/src/popover/popover-content.tsx
  packages/react/src/popover/popover.styles.ts
  packages/react/src/popover/use-popover.ts
Labels: bugfix, pending release

#626 fix(react-pagination): add active page to memoized callback deps
  packages/react/src/use-pagination/index.ts
Labels: reviewing

#773 fix(react-table): props weren't being passed to the table
  packages/react/src/table/table.tsx
Labels: bugfix
