Repository heroui-inc/heroui, pull requests merged in 2022-12, with the labels that each got.

#900 chore: eslint ignore nextjs style unknown-property
  apps/docs/.eslintrc.json
Labels: pending changes

#785 fix(react-transition): animation flickers in react 18
  packages/react/src/popover/popover-content.tsx
  packages/react/src/popover/popover.styles.ts
  packages/react/src/popover/use-popover.ts
  packages/react/src/utils/css-transition.ts
Labels: bugfix

#942 Feat/docs support section
  apps/docs/src/components/features-grid/features-grid.tsx
  apps/docs/src/components/home/index.ts
  apps/docs/src/components/home/support.tsx
  apps/docs/src/components/icons/index.ts
  apps/docs/src/components/icons/link.tsx
  apps/docs/src/components/icons/open-collective.tsx
  apps/docs/src/components/icons/patreon.tsx
  apps/docs/src/components/icons/plus-bold.tsx
  apps/docs/src/components/index.ts
  apps/docs/src/components/sonar-pulse/index.ts
  apps/docs/src/components/sonar-pulse/sonar-pulse.styles.ts
  apps/docs/src/components/sonar-pulse/sonar-pulse.tsx
  apps/docs/src/lib/docs/sponsors.ts
  apps/docs/src/pages/index.tsx
  apps/docs/src/utils/animations.ts
Labels: core, type:docs-src, feature

#944 Pr/839
  packages/react/src/collapse/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/password.test.tsx.snap
  packages/react/src/table/__tests__/index.test.tsx
  packages/react/src/table/table-body.tsx
  packages/react/src/table/table.stories.tsx
  packages/react/src/textarea/__tests__/__snapshots__/index.test.tsx.snap
Labels: bugfix

#945 fix(react-table): layout shifting and table pagination
  packages/react/src/pagination/pagination.tsx
  packages/react/src/table/table-body.tsx
  packages/react/src/table/table.stories.tsx
  packages/react/src/use-pagination/index.ts
Labels: bugfix, pending release

#952 fix(react-link): classnames mismatch during hydration
  packages/react/src/link/link.styles.ts
  packages/react/src/link/link.tsx
  packages/react/src/theme/dark-theme.ts
  packages/react/src/theme/light-theme.ts
Labels: bugfix

#953 fix(react-popover): unknown event property when custom trigger
  packages/react/src/popover/popover-trigger.tsx
Labels: bugfix
