Repository heroui-inc/heroui, pull requests merged in 2022-03, with the labels that each got.

#323 Fix ( Tooltip) Text invert's color error
  packages/react/src/tooltip/tooltip.stories.tsx
  packages/react/src/tooltip/tooltip.styles.ts
Labels: in progress

#325 Make `Pagination` properly controlled.
  packages/react/src/use-pagination/index.ts
Labels: pending changes

#338 Fix input component value type
  apps/docs/content/docs/components/input.mdx
  packages/react/src/collapse/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/password.test.tsx.snap
  packages/react/src/input/input-props.ts
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/textarea/__tests__/__snapshots__/index.test.tsx.snap
Labels: bugfix, waiting next release

#350 fix[react](collapse): wrong close when the content includes a input/t…
  packages/react/src/collapse/collapse.stories.tsx
  packages/react/src/collapse/collapse.styles.ts
  packages/react/src/collapse/collapse.tsx
Labels: core, bugfix, waiting next release

#277 fix(button): Change the default of Button type props
  apps/docs/content/docs/components/button.mdx
  packages/react/src/button/button.tsx
Labels: waiting next release

#360 fix[react](table): animated and hideHeader props destructured
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/table/table-body.tsx
  packages/react/src/table/table-column-header.tsx
  packages/react/src/table/table-row.tsx
  packages/react/src/table/table.tsx
Labels: bugfix, waiting next release

#355 fix[react](root): @react-aria/ssr package version changed to 3.1.2
  packages/react/package.json
  yarn.lock
Labels: bugfix, waiting next release

#367 Button Disabled state now adaptive to Button Variant Set Plus Fix a typo on Table Doc
  apps/docs/content/components/input/helper.ts
  apps/docs/content/docs/components/table.mdx
  packages/react/src/button/button-group.stories.tsx
  packages/react/src/button/button-group.styles.ts
  packages/react/src/button/button.styles.ts
  packages/react/src/button/button.tsx
  packages/react/src/button/utils.tsx
  packages/react/src/css-baseline/css-baseline.tsx
  packages/react/src/theme/common.ts
  yarn.lock
Labels: core, type:nextui, bugfix

#368 Upgrade @stitches/react to 1.2.7
  packages/react/package.json
  yarn.lock
Labels: stitches

#370 fix[react](theme): ConfigType.Theme interface fixed
  packages/react/src/theme/types.ts
Labels: bugfix

#371 fix[react](progress): color default variant
  packages/react/src/progress/progress.styles.ts
Labels: bugfix

#372 chore[react](root): drip exported
  packages/react/src/index.ts
Labels: refactor

#373 fix[react](button): gradient ghost/bordered button with single icon p…
  packages/react/src/button/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/icon.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/button/button-icon.tsx
  packages/react/src/button/button.stories.tsx
  packages/react/src/button/button.styles.ts
  packages/react/src/button/utils.tsx
  packages/react/src/checkbox/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/password.test.tsx.snap
  packages/react/src/spacer/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/textarea/__tests__/__snapshots__/index.test.tsx.snap
Labels: bugfix

#374 v1.0.5-beta.5
  apps/docs/content/docs/components/table.mdx
  apps/docs/package.json
  apps/docs/src/hooks/use-portal.ts
  examples/create-next-app/package.json
  examples/create-react-app/package.json
  examples/vite-react-typescript/package.json
  packages/react/package.json
  packages/react/src/button/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/icon.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/button/button-group.stories.tsx
  packages/react/src/button/button-group.styles.ts
  packages/react/src/button/button-icon.tsx
  packages/react/src/button/button.stories.tsx
  packages/react/src/button/button.styles.ts
  packages/react/src/button/button.tsx
  packages/react/src/button/utils.tsx
  packages/react/src/checkbox/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/css-baseline/css-baseline.tsx
  packages/react/src/index.ts
  packages/react/src/input/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/password.test.tsx.snap
  packages/react/src/progress/progress.styles.ts
  packages/react/src/spacer/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/textarea/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/theme/common.ts
  packages/react/src/theme/types.ts
  packages/storybook/package.json
  yarn.lock
Labels: core, created-by: NextUI team, stitches

#376 Fix#369/modal css error
  packages/react/src/modal/modal.stories.tsx
  packages/react/src/modal/modal.tsx
Labels: bugfix, waiting next release

#377 Fix #288 modal animation behavior
  packages/react/src/backdrop/backdrop.styles.ts
  packages/react/src/backdrop/backdrop.tsx
Labels: type:nextui, bugfix
