Repository heroui-inc/heroui, pull requests merged in 2022-11, with the labels that each got.

#528 chore(repo): upgraded storybook and cleaned up the css type
  apps/docs/src/components/features-grid/features-grid.tsx
  apps/docs/src/components/fixed/index.tsx
  apps/docs/src/components/templates/user-twitter-card/index.tsx
  packages/react/package.json
  packages/react/src/avatar/avatar.tsx
  packages/react/src/backdrop/backdrop.tsx
  packages/react/src/button/button-icon.tsx
  packages/react/src/button/button.tsx
  packages/react/src/button/utils.tsx
  packages/react/src/card/card.tsx
  packages/react/src/col/col.tsx
  packages/react/src/container/container.tsx
  packages/react/src/divider/divider.tsx
  packages/react/src/dropdown/dropdown-menu.tsx
  packages/react/src/grid/grid-container.tsx
  packages/react/src/grid/grid-item.tsx
  packages/react/src/grid/grid.stories.tsx
  packages/react/src/grid/grid.tsx
  packages/react/src/image/image.skeleton.tsx
  packages/react/src/image/image.tsx
  packages/react/src/input/input.tsx
  packages/react/src/loading/loading.tsx
  packages/react/src/modal/modal-footer.tsx
  packages/react/src/modal/modal-header.tsx
  packages/react/src/pagination/pagination-highlight.tsx
  packages/react/src/popover/popover-content.tsx
  packages/react/src/progress/progress.tsx
  packages/react/src/radio/radio-group.tsx
  packages/react/src/radio/radio.tsx
  packages/react/src/row/row.stories.tsx
  packages/react/src/row/row.tsx
  packages/react/src/spacer/spacer.tsx
  packages/react/src/table/table-body.tsx
  packages/react/src/table/table.tsx
  packages/react/src/text/child.tsx
  packages/react/src/textarea/textarea.tsx
  packages/react/src/tooltip/tooltip-content.tsx
  packages/react/src/tooltip/tooltip.tsx
  packages/react/src/user/user.tsx
  packages/react/src/utils/checkmark.tsx
  packages/react/src/utils/expand.tsx
  packages/storybook/package.json
  yarn.lock
Labels: type:storybook, pending changes

#631 Fix: Docs navbar height issue in tablet size
  apps/docs/content/components/card/action.ts
  apps/docs/content/components/card/default.ts
  apps/docs/content/components/link/icon.ts
  apps/docs/src/components/sidebar/category.tsx
  apps/docs/src/components/sidebar/index.tsx
  packages/react/src/card/card.stories.tsx
Labels: bugfix

#723 fix: remove color-scheme suffix (fix #692)
  packages/react/src/theme/utils.ts
  packages/storybook/storybook-static/iframe.html
  packages/storybook/storybook-static/main.e3e09920.iframe.bundle.js
  packages/storybook/storybook-static/main.e3e09920.iframe.bundle.js.LICENSE.txt
Labels: bugfix

#741 fix: Input should not change value itself when value props is set (fix #737
  packages/react/src/input/input.tsx
  packages/storybook/storybook-static/iframe.html
  packages/storybook/storybook-static/main.0039f79a.iframe.bundle.js
  packages/storybook/storybook-static/main.70564690.iframe.bundle.js
  packages/storybook/storybook-static/main.70564690.iframe.bundle.js.LICENSE.txt
  packages/storybook/storybook-static/project.json
Labels: bugfix

#689 feat: Add isDisabled property to tooltip & Fix abnormal props.content display #683
  packages/react/src/tooltip/__test__/index.test.tsx
  packages/react/src/tooltip/tooltip.stories.tsx
  packages/react/src/tooltip/tooltip.tsx
Labels: pending changes

#535 fix(react-modal): animation for backdrop
  packages/react/src/backdrop/backdrop.styles.ts
Labels: resolve conflicts

#678 Disabled `<Input/>` autofill highlighting.
  packages/react/src/input/input.styles.ts
Labels: pending release

#788 fix(react-radio) inaccessible prop types and duplicate class name
  packages/react/src/radio/index.ts
  packages/react/src/radio/radio.tsx
Labels: bugfix, pending release

#800 fix(react-dropdown): add react-stately/collections and react-stately/menu deps
  packages/react/package.json
  yarn.lock
Labels: bugfix, pending release

#807 fix(react-card): footer blur not working on Firefox
  packages/react/src/card/card.styles.ts
Labels: bugfix, pending release

#805 fix: navbar link does not respect parent size
  packages/react/src/navbar/navbar-link.tsx
Labels: bugfix, pending release

#864 fix(react-navbar): collapse wrapper background on safari
  packages/react/src/navbar/navbar.styles.ts
Labels: bugfix, pending release

#866 chore(react): react-aria dependecies upgraded in order to support react 18
  packages/react/package.json
  packages/react/src/avatar/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/avatar/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/icon.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/password.test.tsx.snap
  packages/react/src/link/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/snippet/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/spacer/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/textarea/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/user/__tests__/__snapshots__/index.test.tsx.snap
  yarn.lock
Labels: dependencies, react-aria
