Repository heroui-inc/heroui, pull requests merged in 2022-07, with the labels that each got.

#537 fix(react-tooltip): tooltip story
  apps/docs/content/components/tooltip/trigger.ts
  packages/react/src/tooltip/tooltip.stories.tsx
Labels: reviewing

#594 fix(react-card): box shadow applied intead of box shadow filter on sa…
  packages/react/src/card/card.stories.tsx
  packages/react/src/card/card.styles.ts
Labels: bugfix, pending release

#567 feat(react-container): add forwardRef
  packages/react/src/container/container.tsx
Labels: bugfix, pending release

#564 fix(react-table): react-stately props
  packages/react/src/table/table.tsx
  packages/react/src/utils/prop-types.ts
Labels: bugfix, pending release

#595 fix(react-dropdown): zIndex for focused dropdown item
  packages/react/src/dropdown/dropdown.styles.ts
Labels: refactor

#610 Feat/badge component
  apps/docs/content/components/avatar/icon.ts
  apps/docs/content/components/badge/a11y.ts
  apps/docs/content/components/badge/bordered.ts
  apps/docs/content/components/badge/colors.ts
  apps/docs/content/components/badge/content-offset.ts
  apps/docs/content/components/badge/content-placements.ts
  apps/docs/content/components/badge/content-shape.ts
  apps/docs/content/components/badge/content-visibility.ts
  apps/docs/content/components/badge/content.ts
  apps/docs/content/components/badge/default.ts
  apps/docs/content/components/badge/disable-outline.ts
  apps/docs/content/components/badge/dot.ts
  apps/docs/content/components/badge/flat.ts
  apps/docs/content/components/badge/index.ts
  apps/docs/content/components/badge/points.ts
  apps/docs/content/components/badge/shadow.ts
  apps/docs/content/components/badge/sizes.ts
  apps/docs/content/components/badge/squared.ts
  apps/docs/content/components/button/icon.ts
  apps/docs/content/components/collapse/custom-arrow.ts
  apps/docs/content/components/dropdown/description.ts
  apps/docs/content/components/dropdown/disable-animation.ts
  apps/docs/content/components/dropdown/icon.ts
  apps/docs/content/components/dropdown/sections.ts
  apps/docs/content/components/index.ts
  apps/docs/content/components/input/password.ts
  apps/docs/content/components/switch/icon.ts
  apps/docs/content/components/table/custom-cells.ts
  apps/docs/content/docs/components/badge.mdx
  apps/docs/content/docs/components/button.mdx
  apps/docs/content/docs/components/dropdown.mdx
  apps/docs/content/docs/manifest.json
  apps/docs/src/components/playground/title.tsx
  apps/docs/src/components/sandpack/themes.ts
  apps/docs/src/styles/sandpack.css
  packages/react/.babelrc.js
  packages/react/.jest.config.js
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/avatar/avatar.styles.ts
  packages/react/src/badge/__tests__/index.test.tsx
  packages/react/src/badge/badge.animations.ts
  packages/react/src/badge/badge.stories.tsx
  packages/react/src/badge/badge.styles.ts
  packages/react/src/badge/badge.tsx
  packages/react/src/badge/index.ts
  packages/react/src/collapse/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/css-baseline/css-baseline.tsx
  packages/react/src/index.ts
  packages/react/src/input/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/password.test.tsx.snap
  packages/react/src/table/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/textarea/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/utils/icons.tsx
  packages/react/src/utils/system.ts
  packages/react/tests/jest-setup.js
  packages/react/tests/setup.js
  packages/react/tsconfig.json
  yarn.lock
Labels: pending release, new component

#553 fix: Switch Animation In Safari
  packages/react/src/switch/switch.styles.ts
  packages/react/src/switch/switch.tsx
Labels: bugfix, pending release

#616 fix(react-dropdown): add collections and menu deps of react-stately
  packages/react/package.json
  yarn.lock
Labels: bugfix, react-aria
