Repository heroui-inc/heroui, pull requests merged in 2022-02, with the labels that each got.

#223 fix: sidebar link
  apps/docs/src/components/nav-link/index.tsx
  apps/docs/src/components/sidebar/category.tsx
Labels: type:docs-src, bugfix

#238 chore: update nextjs version
  apps/docs/next-env.d.ts
  apps/docs/package.json
  apps/docs/tsconfig.json
  yarn.lock
Labels: reviewing

#242 fix(textarea): top position on focused
  packages/react/src/input/input.styles.ts
  packages/react/src/textarea/textarea.stories.tsx
Labels: bugfix

#249 Staging - Fix/tree shaking
  .github/workflows/staging.yaml
  package.json
  packages/react/.babelrc.js
  packages/react/package.json
  packages/react/scripts/build.js
  packages/react/scripts/cherry-pick.js
  packages/react/scripts/minify.js
  packages/react/scripts/pre-publish.js
  turbo.json
  yarn.lock
Labels: core

#250 fix(input): label and input id mismatch solved
  packages/react/package.json
  packages/react/src/input/input.stories.tsx
  packages/react/src/input/input.tsx
  packages/react/src/theme/theme-provider.tsx
  yarn.lock
Labels: core, type:nextui, a11y, bugfix

#225 Fix - Make the titles of the card components under "Primary Action" r…
  apps/docs/content/docs/components/card.mdx
Labels: reviewing

#243 Changed grammar errors.
  apps/docs/content/docs/components/avatar.mdx
Labels: pending changes

#264 Refactor/button capitalized
  apps/docs/content/docs/components/button.mdx
  apps/docs/content/docs/guide/getting-started.mdx
  apps/docs/content/docs/theme/dark-mode.mdx
  apps/docs/public/sponsored-by-vercel.svg
  apps/docs/src/components/icons/vercel.tsx
  apps/docs/src/components/vercel-callout/vercel-callout.tsx
  packages/react/README.md
  packages/react/src/button/button.styles.ts
  packages/react/src/text/child.tsx
Labels: fixed: pending release

#236 refactor(button): button focus migrated to @react-aria/focus
  apps/docs/content/docs/components/button.mdx
  apps/docs/content/docs/components/link.mdx
  apps/docs/content/docs/theme/default-theme.mdx
  apps/docs/src/theme/shared.ts
  packages/react/package.json
  packages/react/src/button/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/icon.test.tsx.snap
  packages/react/src/button/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/button/button.styles.ts
  packages/react/src/button/button.tsx
  packages/react/src/collapse/__tests__/__snapshots__/group.test.tsx.snap
  packages/react/src/collapse/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/input/__tests__/__snapshots__/password.test.tsx.snap
  packages/react/src/input/input.styles.ts
  packages/react/src/link/link.styles.ts
  packages/react/src/pagination/pagination.styles.ts
  packages/react/src/progress/progress.styles.ts
  packages/react/src/switch/switch.styles.ts
  packages/react/src/textarea/__tests__/__snapshots__/index.test.tsx.snap
  packages/react/src/theme/common.ts
  packages/react/src/theme/dark-theme.ts
  packages/react/src/theme/light-theme.ts
  packages/react/src/theme/stitches.config.ts
  yarn.lock
Labels: core, a11y, refactor, fixed: pending release

#276 fix(tooltip): Show no content if content is empty
  packages/react/src/tooltip/__test__/index.test.tsx
  packages/react/src/tooltip/tooltip.stories.tsx
  packages/react/src/tooltip/tooltip.tsx
Labels: refactor, pending release

#309 fix: changeTheme function to avoid empty strings
  packages/react/src/theme/utils.ts
Labels: bugfix
