Repository heroui-inc/heroui, pull requests merged in 2024-11, with the labels that each got.

#3657 chore(deps): bump tailwind-merge version
  .changeset/grumpy-mayflies-rhyme.md
  packages/core/theme/package.json
  packages/core/theme/src/utils/cn.ts
  packages/core/theme/src/utils/tw-merge-config.ts
  pnpm-lock.yaml
Labels: 🚥 Status: On Hold

#3938 fix(theme): added stripe color gradients for progress
  .changeset/poor-moose-double.md
  packages/core/theme/src/components/progress.ts
  packages/core/theme/src/plugin.ts
  packages/core/theme/src/utils/tw-merge-config.ts
Labels: 👀 Status: To Review

#3909 fix(theme): apply tw nested group
  .changeset/happy-parrots-search.md
  apps/docs/content/components/table/custom-styles.ts
  packages/core/theme/src/components/table.ts
Labels: 💥 Type: Breaking Change

#3966 fix(input): fixed a sliding issue caused by the helper wrapper
  .changeset/empty-helper-wrapper-div.md
  packages/components/input/src/input.tsx
  packages/components/input/src/textarea.tsx
  packages/components/select/src/select.tsx
Labels: 👀 Status: To Review

#3881 fix(theme): make select styles consistent with input
  .changeset/twelve-trains-smile.md
  packages/core/theme/src/components/input.ts
  packages/core/theme/src/components/select.ts
Labels: 👀 Status: To Review

#3748 feat(input-otp): Adding Input OTP component
  .changeset/spotty-flies-jump.md
  apps/docs/config/routes.json
  apps/docs/content/components/dropdown/variants.raw.jsx
  apps/docs/content/components/index.ts
  apps/docs/content/components/input-otp/allowed-keys.raw.jsx
  apps/docs/content/components/input-otp/allowed-keys.ts
  apps/docs/content/components/input-otp/colors.raw.jsx
  apps/docs/content/components/input-otp/colors.ts
  apps/docs/content/components/input-otp/controlled.raw.jsx
  apps/docs/content/components/input-otp/controlled.ts
  apps/docs/content/components/input-otp/description.raw.jsx
  apps/docs/content/components/input-otp/description.ts
  apps/docs/content/components/input-otp/disabled.raw.jsx
  apps/docs/content/components/input-otp/disabled.ts
  apps/docs/content/components/input-otp/error-message.raw.jsx
  apps/docs/content/components/input-otp/error-message.ts
  apps/docs/content/components/input-otp/index.ts
  apps/docs/content/components/input-otp/password.raw.jsx
  apps/docs/content/components/input-otp/password.ts
  apps/docs/content/components/input-otp/radius.raw.jsx
  apps/docs/content/components/input-otp/radius.ts
  apps/docs/content/components/input-otp/readonly.raw.jsx
  apps/docs/content/components/input-otp/readonly.ts
  apps/docs/content/components/input-otp/required.raw.jsx
  apps/docs/content/components/input-otp/required.ts
  apps/docs/content/components/input-otp/sizes.raw.jsx
  apps/docs/content/components/input-otp/sizes.ts
  apps/docs/content/components/input-otp/usage.raw.jsx
  apps/docs/content/components/input-otp/usage.ts
  apps/docs/content/components/input-otp/variants.raw.jsx
  apps/docs/content/components/input-otp/variants.ts
  apps/docs/content/docs/components/input-otp.mdx
  apps/docs/package.json
  apps/docs/public/sitemap-0.xml
  packages/components/input-otp/README.md
  packages/components/input-otp/__tests__/input-otp.test.tsx
  packages/components/input-otp/package.json
  packages/components/input-otp/src/index.ts
  packages/components/input-otp/src/input-otp-context.ts
  packages/components/input-otp/src/input-otp-segment.tsx
  packages/components/input-otp/src/input-otp.tsx
  packages/components/input-otp/src/use-input-otp.ts
  packages/components/input-otp/stories/input-otp.stories.tsx
  packages/components/input-otp/tsconfig.json
  packages/components/input-otp/tsup.config.ts
  packages/core/react/package.json
  packages/core/react/src/index.ts
  packages/core/theme/src/components/index.ts
  packages/core/theme/src/components/input-otp.ts
  pnpm-lock.yaml
Labels: 🚧 Status: Changes Requested

#3321 fix: move circular-progress tv to progress
  .changeset/angry-maps-serve.md
  packages/core/theme/src/components/circular-progress.ts
  packages/core/theme/src/components/index.ts
  packages/core/theme/src/components/progress.ts
Labels: 💥 Type: Breaking Change
